mongodb/docs-c

source/includes/c-connection-no-stable-api.c, source/includes/c-connection.c, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38960
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-38960-connect-atlas/
=> DOCSP-38960: Add Atlas code to landing page

source/libbson/conf.py, source/libbson/guides/json.txt, source/libbson/includes/examples/bcon-col-view.c, source/libbson/includes/examples/bcon-speed.c, source/libbson/includes/examples/bson-check-depth.c, source/libbson/includes/examples/bson-metrics.c, source/libbson/includes/examples/bson-streaming-reader.c, source/libbson/includes/examples/bson-to-json.c, source/libbson/includes/examples/cmake/find_package/CMakeLists.txt, source/libbson/includes/examples/cmake/find_package_static/CMakeLists.txt, source/libbson/includes/examples/creating.c, source/libbson/includes/examples/hello_bson.c, source/libbson/includes/examples/json-to-bson.c, source/libmongoc/includes/examples/basic_aggregation/basic-aggregation.c, source/libmongoc/includes/examples/cmake/find_package/CMakeLists.txt, source/libmongoc/includes/examples/cmake/find_package_static/CMakeLists.txt, source/libmongoc/includes/examples/common_operations/common-operations.c, source/libmongoc/includes/examples/hello_mongoc.c, source/libmongoc/includes/examples/mongoc-dump.c, source/libmongoc/includes/examples/mongoc-ping.c
JIRA - https://jira.mongodb.org/browse/DOCSP-40978
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-40978-copyright/
=> DOCSP-40978: Update copyright syntax

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-41178
Staging - https://preview-mongodbmongokart.gatsbyjs.io/c/docsp-41178-patch-release/
=> DOCSP-41178 - v1.27.4

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-42231
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-42231-patch-release/
=> DOCSP-42231: v1.27.5 release

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43050>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43050-index/>
=> Address NR feedback

source/databases-collections.txt, source/includes/databases-collections/databases-collections.c, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43062>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43062-databases-collections/databases-collections/>
=> DOCSP-43062: Databases and Collections

snooty.toml, source/includes/usage-examples/retrieve-code-examples.c, source/includes/usage-examples/sample-app-intro.rst, source/includes/usage-examples/sample-read-app.c, source/index.txt, source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43073>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43073-read/read/>
=> DOCSP-43073: Read Data from MongoDB

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-43379
Staging - https://preview-mongodbmongokart.gatsbyjs.io/c/docsp-43379-version-bump/libmongoc/tutorials/obtaining-libraries/from-source/#std-label-build-libraries
=> DOCSP-43379 - version bump

source/includes/read/count.c, source/read.txt, source/read/count.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43078>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43078-count/read/count/>
=> DOCSP-43078: Count documents

source/includes/read/project.c, source/read.txt, source/read/project.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43076>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43076-project/read/project/>
=> DOCSP-43076: Specify Fields to Return

source/includes/read/retrieve.c, source/read.txt, source/read/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43075>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43075-retrieve/read/retrieve/>
=> DOCSP-43075:  Retrieve data

source/includes/read/distinct.c, source/read.txt, source/read/distinct.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43079>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43079-distinct/read/distinct/>
=> DOCSP-43079: Retrieve Distinct Field Values

source/includes/read/specify-documents-to-return.c, source/read.txt, source/read/specify-documents-to-return.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43077>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43077-specify-documents/read/specify-documents-to-return/>
=> DOCSP-43077: Specify Documents to Return

source/includes/read/specify-documents-to-return.c
JIRA - <https://jira.mongodb.org/browse/DOCSP-43077>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/specify-docs-fix/read/specify-documents-to-return/>
=> Fast follow for code fixes

source/databases-collections.txt, source/includes/read/cursors.c, source/read.txt, source/read/cursors.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43080>
Staging - <https://deploy-preview-33--docs-c.netlify.app/read/cursors/>
=> DOCSP-43080: Cursors

source/index.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43091>
Staging - <https://deploy-preview-36--docs-c.netlify.app/whats-new/>
=> DOCSP-43091 Add What's New

source/libmongoc/ref/platforms.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43673>
Staging - <https://deploy-preview-40--docs-c.netlify.app/libmongoc/ref/platforms/>
=> DOCSP-43673: Remove Visual Studio 2013 support

snooty.toml, source/includes/usage-examples/index-code-examples.c, source/includes/usage-examples/sample-indexes-app.c, source/index.txt, source/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43083>
Staging - <https://deploy-preview-42--docs-c.netlify.app/indexes/>
=> DOCSP-43083: Indexes

source/includes/write/insert.c, source/write.txt, source/write/insert.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43067
Staging - https://deploy-preview-44--docs-c.netlify.app/write/insert/
=> DOCSP-43067: Insert documents

snooty.toml, source/includes/indexes/indexes.c, source/indexes/single-field-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43084>
Staging -
* <https://deploy-preview-45--docs-c.netlify.app/work-with-indexes/>
* <https://deploy-preview-45--docs-c.netlify.app/indexes/single-field-index/>
=> DOCSP-43084: Work with Indexes + Single Field Indexes

source/includes/indexes/indexes.c, source/indexes.txt, source/indexes/compound-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43085>
Staging - <https://deploy-preview-46--docs-c.netlify.app/indexes/compound-index/>
=> DOCSP-43085: Compound Indexes

source/includes/write/replace.c, source/write.txt, source/write/replace.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43069
Staging - https://deploy-preview-52--docs-c.netlify.app/write/replace/
=> DOCSP-43069: Replace documents

source/includes/indexes/indexes.c, source/indexes.txt, source/indexes/atlas-search-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43087>
Staging - <https://deploy-preview-58--docs-c.netlify.app/indexes/atlas-search-index/>
=> DOCSP-43087: Atlas Search Indexes

source/connect.txt, source/connect/stable-api.txt, source/includes/connect/stable-api.c
JIRA - https://jira.mongodb.org/browse/DOCSP-43061
Staging - https://deploy-preview-56--docs-c.netlify.app/connect/stable-api/
=> DOCSP-43061 Stable API

source/includes/security/authentication.c, source/security/authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43090
Staging: https://deploy-preview-57--docs-c.netlify.app/security/authentication/
=> DOCSP-43090 - Authentication

source/includes/security/enterprise-authentication.c, source/security/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44004
Staging: https://deploy-preview-62--docs-c.netlify.app/security/enterprise-authentication/
=> DOCSP-44004 - Enterprise Authentication

source/includes/read-write-configuration.c, source/index.txt, source/read-write-configuration.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43064
Staging - https://deploy-preview-65--docs-c.netlify.app/read-write-configuration/
=> DOCSP-43064 replica sets

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-44306
Staging - https://deploy-preview-68--docs-c.netlify.app/
=> DOCSP-44306: 1.28.1 release

snooty.toml, source/includes/security/authentication.c, source/index.txt, source/security.txt, source/security/authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43089
Staging - https://deploy-preview-69--docs-c.netlify.app/security/
=> DOCSP-43089: Security landing page

source/connect.txt, source/databases-collections.txt, source/get-started.txt, source/index.txt, source/indexes.txt, source/monitoring.txt, source/read.txt, source/security.txt, source/work-with-indexes.txt, source/write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44894>
Staging - <https://deploy-preview-72--docs-c.netlify.app/>
Original: https://www.mongodb.com/docs/languages/c/c-driver/upcoming/
=> DOCSP-44894 Shorten TOC Labels

source/index.txt, source/libbson.txt, source/libbson/cross-platform-notes.txt, source/libbson/guides.txt, source/libbson/tutorials.txt, source/libmongoc.txt, source/libmongoc/guides.txt, source/libmongoc/guides/in-use-encryption.txt, source/libmongoc/howto.txt, source/libmongoc/ref.txt, source/libmongoc/tutorials.txt, source/libmongoc/tutorials/obtaining-libraries.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45438>
Staging - https://deploy-preview-75--docs-c.netlify.app/
=> DOCSP-45438 Shorten TOC v1.28

source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45868>
Staging - <https://deploy-preview-81--docs-c.netlify.app/write/transactions/>
=> DOCSP-45868: Parallel operations admonition

source/connect/tls.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46181>
Staging - <https://deploy-preview-82--docs-c.netlify.app/connect/tls/>
=> DOCSP-46181: Clarify TLS CA file information

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-47823>
Staging - <https://deploy-preview-85--docs-c.netlify.app/install-from-source/#choose-a-version>
=> DOCSP-47823 v1.30.1 Release

.github/workflows/vale-tdbx.yml, source/index.txt, source/read.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48025
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
=> [C] Remove "MongoDB" from page title

source/includes/indexes/indexes.c, source/indexes/atlas-search-index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41555
Staging - https://deploy-preview-84--docs-c.netlify.app/indexes/atlas-search-index/
=> DOCSP-41555: Atlas vector search

source/read/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48204>
Staging - <https://deploy-preview-91--docs-c.netlify.app/read/retrieve/>
=> DOCSP-48204: Fix 404 link

source/get-started.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48499
Staging - https://deploy-preview-97--docs-c.netlify.app/get-started/#run-a-sample-query
=> DOCSP-48499: Get started rendering fix

source/includes/write/gridfs.c
JIRA - https://jira.mongodb.org/browse/DOCSP-48492
Staging - https://deploy-preview-98--docs-c.netlify.app/write/gridfs/
=> DOCSP-48492: Remove bson_as_json

.github/pull_request_template.md, .github/workflows/add-netlify-links.yml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48770>
=> DOCSP-48770 add netlify workflow

source/get-started.txt, source/includes/get-started/CMakeLists.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48728
Staging - https://deploy-preview-104--docs-c.netlify.app/get-started/
Waiting on CDRIVER-5931 to merge.
=> DOCSP-48728: CMake project instructions

.github/pull_request_template.md
JIRA - <https://jira.mongodb.org/browse/DOCSP-48931>
No pages to preview
=> [C] Add a PR checklist item for checking page titles

source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49148>
<li><a href=https://deploy-preview-109--docs-c.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-49148 v1.30.3 release

source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
<li><a href=https://deploy-preview-110--docs-c.netlify.app/async-c-driver>async-c-driver</a></li><li><a href=https://deploy-preview-110--docs-c.netlify.app/get-started>get-started</a></li><li><a href=https://deploy-preview-110--docs-c.netlify.app/index>index</a></li><li><a href=https://deploy-preview-110--docs-c.netlify.app/indexes/atlas-search-index>indexes/atlas-search-index</a></li><li><a href=https://deploy-preview-110--docs-c.netlify.app/read-write-configuration>read-write-configuration</a></li><li><a href=https://deploy-preview-110--docs-c.netlify.app/read>read</a></li><li><a href=https://deploy-preview-110--docs-c.netlify.app/read/change-str …
=> [Backport V1.30] DOCSP-49148 v1.30.3 release

source/get-started.txt, source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49692>
<li><a href=https://deploy-preview-117--docs-c.netlify.app/upgrade>upgrade</a></li><li><a href=https://deploy-preview-117--docs-c.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-49692: Upgrade guide updates

snooty.toml, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-49809
https://deploy-preview-118--docs-c.netlify.app/whats-new/
=> DOCSP-49809: 1.30.4 release

snooty.toml, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-49812
<li><a href=https://deploy-preview-119--docs-c.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-49812: v2.0.1 release

source/connect.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48546>
<li><a href=https://deploy-preview-121--docs-c.netlify.app/connect>connect</a></li>
=> DOCSP-48546: Add AWS Lambda link

source/get-started.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50490
<li><a href=https://deploy-preview-122--docs-c.netlify.app/get-started>get-started</a></li>
=> DOCSP-50490: Homebrew warning for 2.0

snooty.toml, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50591>
[What's New](https://deploy-preview-123--docs-c.netlify.app/whats-new/)
=> DOCSP-50591 v1.30.5 Release

snooty.toml, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50594>
<li><a href=https://deploy-preview-124--docs-c.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-5094 v2.0.2 Release
