source/includes/read/specify-a-query.c, source/read.txt, source/read/count.txt, source/read/distinct.txt, source/read/retrieve.txt, source/read/specify-a-query.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43074>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/c/DOCSP-43074-specify-query/read/specify-a-query/>
=> DOCSP-43074: Specify a Query

snooty.toml, source/get-started.txt, source/get-started/connect-to-mongodb.txt, source/get-started/create-a-connection-string.txt, source/get-started/create-a-deployment.txt, source/get-started/download-and-install.txt, source/get-started/next-steps.txt, source/includes/get-started/troubleshoot.rst, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43052
https://jira.mongodb.org/browse/DOCSP-43051
Staging - 
[Get Started](https://deploy-preview-32--docs-c.netlify.app/get-started/)
[Install](https://deploy-preview-32--docs-c.netlify.app/get-started/download-and-install/)
=> DOSCP-43051 Get Started landing and Install

source/aggregation.txt, source/get-started.txt, source/includes/aggregation/aggregation.c, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43088>
Staging - <https://deploy-preview-38--docs-c.netlify.app/aggregation/>
=> DOCSP-43088: Aggregations

source/includes/read/change-streams.c, source/read.txt, source/read/change-streams.txt, source/read/specify-documents-to-return.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43081>
Staging - <https://deploy-preview-37--docs-c.netlify.app/read/change-streams>
=> DOCSP-43081: Change Streams

source/index.txt, source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43092>
Staging - <https://deploy-preview-50--docs-c.netlify.app/upgrade/>
=> DOCSP-43092 Upgrade versions

source/includes/write/delete.c, source/write.txt, source/write/delete.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43070
Staging - https://deploy-preview-53--docs-c.netlify.app/write/delete/
=> DOCSP-43070: Delete documents

source/includes/write/bulk-write.c, source/write.txt, source/write/bulk-write.txt, source/write/update.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43071
Staging - https://deploy-preview-54--docs-c.netlify.app/write/bulk-write/
=> DOCSP-43071: Bulk operations

source/includes/indexes/indexes.c, source/indexes.txt, source/indexes/multikey-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43086>
Staging - <https://deploy-preview-47--docs-c.netlify.app/indexes/multikey-index/>
=> DOCSP-43086: Multikey Indexes

source/connect.txt, source/includes/connect/compression-tabs.rst, source/includes/connect/disable-host-verification-tabs.rst, source/includes/connect/tls-tabs.rst, source/includes/connect/zlib-level-tabs.rst, source/includes/usage-examples/connect-sample-app.c
Fill out root page for "Connect to MongoDB" (created as stub in [this ticket](http://example.com/)).
A/C: I can see all the operations for connecting to MongoDB in a section.
JIRA - <https://jira.mongodb.org/browse/DOCSP-43745>
Staging - <https://deploy-preview-61--docs-c.netlify.app/connect/>
=> (DOCSP-43745) Connect to MongoDB

source/includes/monitoring/sdam.c, source/index.txt, source/monitoring.txt, source/monitoring/cluster-monitoring.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43082
Staging - https://deploy-preview-63--docs-c.netlify.app/monitoring/cluster-monitoring/
=> DOCSP-43082: Cluster monitoring

snooty.toml, source/databases-collections.txt, source/databases-collections/time-series.txt, source/includes/databases-collections/timeseries.c
JIRA - https://jira.mongodb.org/browse/DOCSP-43063
Staging - https://deploy-preview-55--docs-c.netlify.app/databases-collections/time-series/
=> DOCSP-43063 Time Series Data

source/includes/usage-examples/run-command.c, source/index.txt, source/run-command.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43056>
Staging - <https://deploy-preview-64--docs-c.netlify.app/run-command/>
=> DOCSP-43056 Run a command

source/includes/write/transactions.c, source/write.txt, source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43095>
Staging - <https://deploy-preview-59--docs-c.netlify.app/write/transactions/>
=> DOCSP-43095: Transactions

source/connect.txt, source/connect/connection-targets.txt, source/connect/tls.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44514
Staging - https://deploy-preview-71--docs-c.netlify.app/connect/
=> DOCSP-44514 Add links to connection landing page

source/read-write-configuration.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48212>
Staging - <https://deploy-preview-92--docs-c.netlify.app/read-write-configuration/#read-concern>
=> DOCSP-48212 fix read concern link

source/async-c-driver.txt, source/includes/async-c-driver-example.c, source/index.txt
Context: Ported over https://docs.google.com/document/d/1uCNyMKr5vBVil0i2WsnwaAGl-Z3qO9C3nVCgzCGpvCw/edit?tab=t.0#heading=h.tfw7my94k51h to our docs. 
JIRA - <https://jira.mongodb.org/browse/DOCSP-48179>
Staging - <https://deploy-preview-90--docs-c.netlify.app/async-c-driver/>
=> DOCSP-48179 add async c driver page

source/read/change-streams.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47836>
Staging - <https://deploy-preview-96--docs-c.netlify.app/read/change-streams/#modify-watch-behavior>
=> DOCSP-47836 clarify batchsize description

source/install-from-source.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48572
Staging - https://deploy-preview-101--docs-c.netlify.app/install-from-source/#configuring-for-libbson
=> DOCSP-48572 Remove automatic init

source/includes/security/auth-properties-commas.rst, source/security/authentication.txt, source/security/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48751
<li><a href=https://deploy-preview-106--docs-c.netlify.app/security/authentication>security/authentication</a></li><li><a href=https://deploy-preview-106--docs-c.netlify.app/security/enterprise-authentication>security/enterprise-authentication</a></li>
=> DOCSP-48751: Disallow comma in authMechanismProperties

source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48763>
<li><a href=https://deploy-preview-114--docs-c.netlify.app/connect/connection-targets>connect/connection-targets</a></li>
=> DOCSP-48763: Docker note

config/redirects
Added redirects for all the old Getting Started pages. 
JIRA - <https://jira.mongodb.org/browse/DOCSP-49133>
No pages to preview
=> DOCSP-49133 Fix Old Connect to MongoDB Redirect

source/compatibility.txt, source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-51041>
<li><a href=https://deploy-preview-129--docs-c.netlify.app/compatibility>compatibility</a></li><li><a href=https://deploy-preview-129--docs-c.netlify.app/upgrade>upgrade</a></li><li><a href=https://deploy-preview-129--docs-c.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-51041: drop debian 9 & 10

source/connect/tls.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-51853
<li><a href=https://deploy-preview-131--docs-c.netlify.app/connect/tls>connect/tls</a></li>
=> DOCSP-51853: Update client certificate info

.github/pull_request_template.md, README.rst
Redirect users to the monorepo.
=> [C] Add monorepo notification
